name: OWASP ZAP SARIF Scan with Authentication

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight UTC

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run OWASP ZAP with Context
      - name: Run OWASP ZAP with Context
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk/ \
            ghcr.io/zaproxy/zaproxy zap-full-scan.py \
            -t https://mrunlikeliest.github.io/vulnerable-web-app/ \
            -n /zap/wrk/.zap/web-app.context \
            -r zap-report.html \
            -J zap-report.json \
            -w zap-output.sarif \
            -U TestUser

      # Step 3: Upload SARIF to GitHub Security Dashboard
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: zap-output.sarif

      # Step 4: Upload HTML Report as Artifact (Optional)
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-html-report
          path: zap-report.html
